In [2]:
import numpy as np

## 形状和转换

在 `numpy` 中，数组（array）通常是多维的。我们通常将一维数组称为向量，二维数组称为矩阵，而超过二维的数组称为张量。由于数组可能具有多个维度，因此改变其形状和转换是非常基础且常见的操作。

在本节中，我们将探讨以下三个方面：

- 改变形状（Reshaping）
- 反序（Reversing）
- 转置（Transposing）

其中，改变形状和转置是非常常见的操作，值得深入学习和掌握。

### 改变形状

在本小节中，我们将介绍一些非常高频的 API，特别是用于扩展一维度的 `expand_dims` 和去除一维度的 `squeeze` 函数。这些函数在神经网络的架构中尤其常见。

需要特别注意的是，无论是扩展还是压缩维度，改变的维度大小必须是 1。例如，在使用 `squeeze` 函数时，如果指定了具体的维度，那么该维度的大小必须是 1。

In [6]:
# 创建一个随机整数数组
rng = np.random.default_rng(seed=42)  # 创建一个随机数生成器，种子为 42
arr = rng.integers(1, 100, (3, 4))  # 生成一个 3x4 的整数数组，数值范围是 1 到 100
print(arr)

[[ 9 77 65 44]
 [43 86  9 70]
 [20 10 53 97]]


#### `np.expand_dims`

`np.expand_dims` 函数可以在指定位置增加一个维度。

In [6]:
# 在第二个维度位置增加一个维度
arr_expanded = np.expand_dims(arr, axis=1)
print(arr_expanded.shape)

(3, 1, 4)


输出的形状是 `(3, 1, 4)`，在原来的基础上增加了一个维度。

In [9]:
# 在多个位置增加维度
expanded = np.expand_dims(arr, axis=(1, 3, 4))
print(expanded.shape)

(3, 1, 4, 1, 1)


输出的形状是 `(3, 1, 4, 1, 1)`，在指定的多个位置增加了维度。

In [8]:
# 注意：扩充维度时不能跳过已有的维度
# 下面的代码会出错，因为没有维度 8 可以扩展
# expanded = np.expand_dims(arr, axis=(1, 3, 8))

#### `np.squeeze`

`np.squeeze` 函数用于移除数组形状中大小为 1 的维度。

In [10]:
# 移除第二个维度，因为它的大小为 1
arr_squeezed = np.squeeze(expanded, axis=1)
print(arr_squeezed.shape)

(3, 4, 1, 1)


输出的形状是 `(3, 4, 1, 1)`，移除了一个大小为 1 的维度。

In [11]:
# 移除所有大小为 1 的维度
squeezed = np.squeeze(expanded)
print(squeezed.shape)

(3, 4)


输出的形状是 `(3, 4)`，移除了所有大小为 1 的维度。

#### `np.reshape/arr.reshape`

`reshape` 函数可以改变数组的形状而不改变其数据。

In [13]:
arr

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

In [12]:
# 将数组重塑为另一个形状
arr_reshaped = arr.reshape(2, 2, 3)
print(arr_reshaped)

[[[ 9 77 65]
  [44 43 86]]

 [[ 9 70 20]
  [10 53 97]]]


输出的数组形状是 `(2, 2, 3)`，即重塑为一个三维数组。

In [14]:
# 使用 -1 可以自动计算该维度的大小
arr_reshaped = arr.reshape((4, -1))
print(arr_reshaped)

[[ 9 77 65]
 [44 43 86]
 [ 9 70 20]
 [10 53 97]]


输出的数组形状是 `(4, 3)`，`-1` 表示自动计算该维度的大小。

In [16]:
# 如果尝试将数组重塑为元素数量不匹配的形状，将会出错
# 下面的代码将会引发错误，因为原数组有 12 个元素，而新形状只能容纳 9 个元素
# arr_reshaped = arr.reshape(3, 3)

In [17]:
# 使用 resize 可以改变数组本身的形状
# 注意：resize 会直接修改原数组，而不是返回一个新数组
# 与 reshape 不同，resize 允许新形状的总元素数量与原数组不同
arr.resize((4, 3), refcheck=False)
print(arr)

[[ 9 77 65]
 [44 43 86]
 [ 9 70 20]
 [10 53 97]]


输出的数组形状是 `(4, 3)`，`resize` 还可以填充或截断原数组以匹配新的形状。

In [18]:
# 使用 np.resize 可以创建一个新数组，它的行为略有不同
arr_resized = np.resize(arr, (5, 3))
print(arr_resized)

[[ 9 77 65]
 [44 43 86]
 [ 9 70 20]
 [10 53 97]
 [ 9 77 65]]


输出的数组形状是 `(5, 3)`。如果新形状的总元素数量少于原数组，则 `np.resize` 会复制原数组中的元素以填充新数组。

In [19]:
# 如果新形状的总元素数量多于原数组，则 np.resize 会截断原数组中的元素
arr_resized = np.resize(arr, (2, 2))
print(arr_resized)

[[ 9 77]
 [65 44]]


输出的数组形状是 `(2, 2)`，多余的元素被截断。

### 反序

反序是将数组中的元素顺序颠倒。在 `numpy` 中，我们可以使用切片的方式来实现反序。

如果给您一个字符串或数组让您反序，您可能会想到使用 `reversed` 函数，或者编写一个自定义函数，或者利用 Python 列表的切片功能。在 `numpy` 中，我们可以使用类似的切片方法来反序数组。

In [49]:
# 反序字符串
s = "uevol"
s_reversed = s[::-1]
print(s_reversed)

loveu


In [50]:
# 反序列表
lst = [1, "1", 5.2]
lst_reversed = lst[::-1]
print(lst_reversed)

[5.2, '1', 1]


In [51]:
# 反序 numpy 数组
# 默认情况下，使用切片 -1 可以反序数组的最外层维度
arr_reversed = arr[::-1]
print(arr_reversed)

[[10 53 97]
 [ 9 70 20]
 [44 43 86]
 [ 9 77 65]]


In [21]:
# 可以在不同的维度上进行反序操作
# 例如，反序所有维度
arr_reversed_all_dims = arr[::-1, ::-1]
print(arr_reversed_all_dims)

[[97 53 10]
 [20 70  9]
 [86 43 44]
 [65 77  9]]


### 转置

转置是线性代数中的一个基本操作，它将矩阵的行与列交换。在 `numpy` 中，这个操作可以很容易地通过 `.T` 属性或 `np.transpose` 函数来完成。

需要注意的是，一维数组的转置与原数组相同，因为它只有一个维度。

In [52]:
# 一维数组的转置
arr_1d = np.array([1, 2])
print(arr_1d.T.shape)

(2,)


输出的形状仍然是 `(2,)`，因为一维数组的转置不会改变其形状。

In [53]:
arr

array([[ 9, 77, 65],
       [44, 43, 86],
       [ 9, 70, 20],
       [10, 53, 97]], dtype=int64)

In [23]:
# 多维数组的转置
arr_transposed = arr.T
print(arr_transposed)

[[ 9 44  9 10]
 [77 43 70 53]
 [65 86 20 97]]


输出的数组是原数组的转置，即行和列被交换了

#### `arr.T`

`arr.T` 是转置的简便方法，适用于二维数组。对于多维数组，它会将所有维度的顺序倒置。

#### `np.transpose`

`np.transpose` 函数提供了更多的灵活性，允许您指定转置的维度顺序。

In [25]:
# 使用 np.transpose 进行转置
arr_transposed = np.transpose(arr)
print(arr_transposed)

[[ 9 44  9 10]
 [77 43 70 53]
 [65 86 20 97]]
