In [28]:
import numpy as np

## 矩阵和运算

这一节我们将聚焦矩阵和相关的运算，主要包括：

- 算术（四则运算及其他基础算术）
- 矩阵相关

这些内容在实际应用中非常普遍，我们经常使用这些操作，而且它们非常简单。虽然我们这里不涉及高维度的计算，但逻辑是一致的，只是更加复杂。

### 算术

⭐ 所有的算术函数都可以直接应用于数组（array）。


In [40]:
rng = np.random.default_rng(42)
arr = rng.integers(1, 20, (3, 4))
arr

array([[ 2, 15, 13,  9],
       [ 9, 17,  2, 14],
       [ 4,  2, 11, 19]], dtype=int64)

In [3]:
# +-*/ 四则运算，就像计算两个数字一样
arr * 2

array([[ 4, 30, 26, 18],
       [18, 34,  4, 28],
       [ 8,  4, 22, 38]], dtype=int64)

In [43]:
# 平方也可以
arr ** 2

array([[  4, 225, 169,  81],
       [ 81, 289,   4, 196],
       [ 16,   4, 121, 361]], dtype=int64)

In [35]:
# 开方
np.sqrt(arr)

array([[1.41421356, 3.87298335, 3.60555128, 3.        ],
       [3.        , 4.12310563, 1.41421356, 3.74165739],
       [2.        , 1.41421356, 3.31662479, 4.35889894]])

In [6]:
# 对数
np.log(arr)

array([[0.69314718, 2.7080502 , 2.56494936, 2.19722458],
       [2.19722458, 2.83321334, 0.69314718, 2.63905733],
       [1.38629436, 0.69314718, 2.39789527, 2.94443898]])

In [44]:
arr

array([[ 2, 15, 13,  9],
       [ 9, 17,  2, 14],
       [ 4,  2, 11, 19]], dtype=int64)

In [7]:
# 超过5的都换成5
np.minimum(arr, 5)

array([[2, 5, 5, 5],
       [5, 5, 2, 5],
       [4, 2, 5, 5]], dtype=int64)

In [8]:
# 低于5的都换成5
np.maximum(arr, 5)

array([[ 5, 15, 13,  9],
       [ 9, 17,  5, 14],
       [ 5,  5, 11, 19]], dtype=int64)

In [9]:
# 四舍五入
np.round(np.sqrt(arr), 2)

array([[1.41, 3.87, 3.61, 3.  ],
       [3.  , 4.12, 1.41, 3.74],
       [2.  , 1.41, 3.32, 4.36]])

In [10]:
# floor/ceil
np.floor(np.sqrt(arr))

array([[1., 3., 3., 3.],
       [3., 4., 1., 3.],
       [2., 1., 3., 4.]])

In [11]:
np.ceil(np.sqrt(arr))

array([[2., 4., 4., 3.],
       [3., 5., 2., 4.],
       [2., 2., 4., 5.]])

In [12]:
# mod <=> x % 3
np.mod(arr, 3)

array([[2, 0, 1, 0],
       [0, 2, 2, 2],
       [1, 2, 2, 1]], dtype=int64)

In [13]:
arr-5

array([[-3, 10,  8,  4],
       [ 4, 12, -3,  9],
       [-1, -3,  6, 14]], dtype=int64)

### 矩阵

⭐ 这一小节主要介绍线性代数中矩阵的处理，我们会介绍几个常用的矩阵操作。

In [45]:
rng = np.random.default_rng(42)
a = rng.integers(1, 10, (3, 2))
b = rng.integers(1, 10, (2, 4))
c = rng.integers(1, 10, (3, 3))
a, b, c

(array([[1, 7],
        [6, 4],
        [4, 8]], dtype=int64),
 array([[1, 7, 2, 1],
        [5, 9, 7, 7]], dtype=int64),
 array([[7, 8, 5],
        [2, 8, 5],
        [5, 4, 2]], dtype=int64))

In [37]:
def matrix_multiply(matrix1, matrix2):
    '''
    矩阵乘法
    matrix1：（3，4）
    matrix2：（4，6）
    则结果为：（3，6）
    '''
    rows1 = len(matrix1)
    cols1 = len(matrix1[0])
    rows2 = len(matrix2)
    cols2 = len(matrix2[0])

    if cols1 != rows2:
        # 左列=右行
        raise ValueError("The number of columns in matrix1 must be equal to the number of rows in matrix2.")

    result = [[0 for _ in range(cols2)] for _ in range(rows1)]

    for i in range(rows1):
        for j in range(cols2):
            for k in range(cols1):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

#### `arr.dot`


In [46]:
a,b

(array([[1, 7],
        [6, 4],
        [4, 8]], dtype=int64),
 array([[1, 7, 2, 1],
        [5, 9, 7, 7]], dtype=int64))

In [47]:
matrix_multiply(a,b)

[[36, 70, 51, 50], [26, 78, 40, 34], [44, 100, 64, 60]]

In [16]:
# 数组乘法
np.dot(a, b)

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [17]:
# 或者这样乘
a.dot(b)

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

#### `np.matmul`

In [19]:
# 矩阵乘法
np.matmul(a, b)

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [48]:
# 同上，写起来比较好看的方法
a @ b

array([[ 36,  70,  51,  50],
       [ 26,  78,  40,  34],
       [ 44, 100,  64,  60]], dtype=int64)

In [24]:
# 内积
np.inner(a, a)

array([[50, 34, 60],
       [34, 52, 56],
       [60, 56, 80]], dtype=int64)

In [25]:
# 对，就是内积
a.dot(a.T)

array([[50, 34, 60],
       [34, 52, 56],
       [60, 56, 80]], dtype=int64)

In [26]:
# 行列式
np.linalg.det(c)

-19.999999999999996

In [27]:
# 逆矩阵（方阵）
np.linalg.inv(c)

array([[ 2.00000000e-01, -2.00000000e-01, -2.53765263e-16],
       [-1.05000000e+00,  5.50000000e-01,  1.25000000e+00],
       [ 1.60000000e+00, -6.00000000e-01, -2.00000000e+00]])