In [12]:
import numpy as np

## Numpy中的视图操作

本节主要介绍Numpy中的视图操作。视图操作是指在不复制数组的情况下创建数组的新视图，这意味着新数组与原始数组共享相同的数据存储空间。视图操作在处理大型数组时非常有用，因为它们可以节省内存并提高性能。

### 什么是视图操作？

视图操作允许我们以不同的方式查看和操作数组的数据，而不会创建新的数组对象。通过创建数组的视图，我们可以改变数组的维度、形状、步长和数据类型，以满足不同的需求。

### 创建数组的视图

⭐ 在Numpy中，我们可以使用多种方式创建数组的视图。下面介绍了一些常用的方法：

#### 切片操作

使用切片操作可以创建原始数组的一个子数组视图。切片操作通过指定起始索引、结束索引和步长来选择数组的子集。下面是一个简单的示例：

In [13]:
arr = np.array([1, 2, 3, 4, 5])
view = arr[1:4]  # 创建 arr 的一个视图，包含索引 1 到 3 的元素
print(view)  # 输出: [2 3 4]

[2 3 4]


In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
view[0]=99

In [17]:
arr

array([ 1, 99,  3,  4,  5])

在这个示例中，我们使用切片操作 `arr[1:4]` 创建了原始数组 `arr` 的一个视图 `view`，该视图包含了索引 1 到 3 的元素。通过打印视图，我们可以看到输出结果为 `[2 3 4]`。

#### reshape操作

使用reshape操作可以改变数组的形状，而不改变数组的数据。reshape操作返回一个新的数组视图，该视图具有与原始数组相同的数据，但具有不同的形状。下面是一个示例：

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
view = arr.reshape(2, 3)  # 创建一个 2x3 的数组视图
print(view)

[[1 2 3]
 [4 5 6]]


在这个示例中，我们使用reshape操作 `arr.reshape(2, 3)` 创建了原始数组 `arr` 的一个 2x3 的数组视图 `view`。

#### transpose操作

使用transpose操作可以交换数组的维度，返回一个新的数组视图。transpose操作不会改变数组的数据，只会改变数据的排列方式。下面是一个示例：

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
view = arr.transpose()  # 创建 arr 的转置视图
print(view)

[[1 4]
 [2 5]
 [3 6]]


在这个示例中，我们使用transpose操作 `arr.transpose()` 创建了原始数组 `arr` 的转置视图 `view`。

#### flatten操作

使用flatten操作可以将多维数组转换为一维数组，返回一个新的数组视图。flatten操作不会改变数组的数据，只会改变数据的排列方式。下面是一个示例：

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
view = arr.flatten()  # 创建 arr 的一维数组视图
print(view)  # 输出: [1 2 3 4 5 6]

[1 2 3 4 5 6]


在这个示例中，我们使用flatten操作 `arr.flatten()` 创建了原始数组 `arr` 的一维数组视图 `view`。

#### view操作

使用view操作可以创建一个新的数组视图，该视图与原始数组共享相同的数据存储空间。view操作可以改变数组的形状、步长和数据类型。下面是一个示例：

In [6]:
arr = np.array([1, 2, 3, 4, 5])
view = arr.view(dtype=np.int32)  # 创建 arr 的一个视图，数据类型为int32
print(view)  # 输出: [1 2 3 4 5]

[1 2 3 4 5]


在这个示例中，我们使用view操作 `arr.view(dtype=np.int32)` 创建了原始数组 `arr` 的一个视图 `view`，并指定了数据类型为int32。