In [2]:
import numpy as np

## NumPy 广播机制

NumPy 的广播机制允许不同形状的数组在算术运算中进行兼容。当进行算术运算如加、减、乘、除等操作时，NumPy 试图让这些数组的形状匹配，如果可能的话，会“广播”较小数组的形状以匹配较大数组的形状。这让我们可以在不同形状的数组之间进行数学运算，而无需手动调整它们的大小。

### 直观认识

想象一下你有一个形状为 (3,) 的一维数组，也就是有3个元素的向量，和一个单独的数字（可以认为是形状为 (1,) 的数组）。如果你想要把这个单独的数字加到向量的每一个元素上，按照数学上的直觉，你可能需要写一个循环，逐个元素地进行加法。但是在NumPy中，你不需要写循环，你只需要简单地执行加法运算，NumPy会自动把那个单独的数字“扩展”或者说“广播”到向量的每一个元素上，然后逐个相加。

### 广播的规则

NumPy 在进行广播时遵循以下规则：

1. 如果所有输入数组的维数不相同，将形状较小的数组的形状在前面补1，直到所有的数组维数都相同。
2. 在任何一个维度上，如果一个数组的大小是1，而另一个数组的大小大于1，则第一个数组的形状会沿着这个维度扩展以匹配另一个数组的形状。
3. 如果在任何维度上，两个数组的大小不一致且其中一个数组的大小不是1，则无法进行广播，NumPy将会抛出错误。

接下来，让我们通过代码示例来具体看看广播是如何工作的。

首先，我们创建了一个形状为 `(3, 4)` 的随机整数数组 `a`。

In [3]:
# 创建一个随机数生成器
rng = np.random.default_rng(seed=42)

In [4]:
# 创建一个 3x4 的随机整数数组
a = rng.integers(1, 100, (3, 4))
a

array([[ 9, 77, 65, 44],
       [43, 86,  9, 70],
       [20, 10, 53, 97]], dtype=int64)

这将输出一个形状为 `(3, 4)` 的数组，即有3行4列。

现在，我们尝试将数组 `a` 与一个形状为 `(4,)` 的一维数组进行相加。这里，一维数组的形状将会在前面补1，变成 `(1, 4)`。然后，这个一维数组沿着第一个维度（行）广播，以匹配 `a` 的形状 `(3, 4)`。

In [10]:
# 将 a 数组与一个一维数组 [1,2,3,4] 相加
# 一维数组的形状会被广播以匹配 a 的形状
b = np.array([1, 2, 3, 4])
b1 = np.array([[1, 2, 3, 4]])
b2 = np.array([[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]])
a + b, a + b1, a + b2

(array([[ 10,  79,  68,  48],
        [ 44,  88,  12,  74],
        [ 21,  12,  56, 101]], dtype=int64),
 array([[ 10,  79,  68,  48],
        [ 44,  88,  12,  74],
        [ 21,  12,  56, 101]], dtype=int64),
 array([[ 10,  79,  68,  48],
        [ 44,  88,  12,  74],
        [ 21,  12,  56, 101]], dtype=int64))

结果是，一维数组 `[1, 2, 3, 4]` 被广播到每一行，与 `a` 的每一行相加。

在另一个例子中，我们将 `a` 与一个形状为 `(3, 1)` 的二维数组进行相加。这里，二维数组沿着第二个维度（列）广播，以匹配 `a` 的形状。

In [6]:
# 将 a 数组与一个形状为 (3, 1) 的二维数组相加
# 二维数组的形状会被广播以匹配 a 的形状
a + [[1], [2], [3]]

array([[ 10,  78,  66,  45],
       [ 45,  88,  11,  72],
       [ 23,  13,  56, 100]], dtype=int64)

结果是，二维数组 `[[1], [2], [3]]` 被广播到每一列，与 `a` 的每一列相加。

通过这些示例，我们可以看到 NumPy 如何灵活地处理不同形状的数组，并在算术运算中自动应用广播机制。这大大简化了数组操作，使得代码更加简洁易读。